version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/private
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: csym019db
      MYSQL_USER: student
      MYSQL_PASSWORD: csym019
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
