version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: student
      MYSQL_PASSWORD: csym019
      MYSQL_DB: Internet_programming

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Internet_programming
      MYSQL_USER: student
      MYSQL_PASSWORD: csym019
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080      

volumes:
  db_data: